name: React Deployment On AWS-S3-Bucket
on:
  push:
    branches: [main]      
jobs:
  build:
    name: Code-Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      
      - name: Install Dependencies
        run: npm install      
      
      - name: Build
        env:
          CI: false          
          #If CI is true, then any warning in the application/code will be treated as error. and eventually it'll fail the p
        run: npm run build
        
      - name: Test
        run: npm test

      - name: List directory
        run: ls
        
  deploy:
    name: Deploy to S3
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: List directory
        run: ls        
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'build/'      # optional: defaults to entire repository
